# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 22:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('attending_sangeet', models.BooleanField(default=False)),
                ('attending_ceremony', models.BooleanField(default=False)),
                ('attending_reception', models.BooleanField(default=False)),
                ('meal_choice', models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-vegetarian')], max_length=7)),
                ('note', models.TextField(blank=True, max_length=500)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('invited_by', models.CharField(choices=[('verma', 'Verma Family'), ('gupta', 'Gupta Family')], max_length=5)),
                ('invited_sangeet', models.BooleanField(default=False)),
                ('invited_ceremony', models.BooleanField(default=False)),
                ('invited_reception', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
            },
        ),
    ]
