# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_added_guest_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='attending_ceremony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='attending_reception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='attending_sangeet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='invited_by',
            field=models.CharField(choices=[('verma', 'Verma Family'), ('gupta', 'Gupta Family')], default='gupta', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='invited_ceremony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='invited_reception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='invited_sangeet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='meal_choice',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-vegetarian')], default='veg', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='name',
            field=models.CharField(default=' ', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='note',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
