# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_add_blank_and_null_conditions_to_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invitation.Invitation'),
        ),
    ]
