# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitation', '0002_added_non_relation_fields_to_guest_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
