# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_swapped_invitation_field_to_relation_to_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
