# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_add_guest_invite_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='invite',
            new_name='invitation',
        ),
    ]
