# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_make_name_on_invitation_model_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together=set([('name', 'invitation')]),
        ),
    ]
