# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005__add_unique_together_constraint_on_guest_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='meal_choice',
            field=models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-vegetarian')], max_length=7),
        ),
    ]
