# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0007_name_on_invitation_now_a_slugfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='rsvp',
            field=models.BooleanField(default=False),
        ),
    ]
